[build]
incremental = true

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=x86-64"]

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 2
lto = "thin"
codegen-units = 16
strip = true
